name: crystal-gchat-server
version: "1.3.5"
summary: Crystal Lang GlobalChat2 Server
description: Custom encrypted chat with live drawing

grade: stable
confinement: strict
base: core18

apps:
  crystal-gchat-server:
    command: bin/crystal-gchat-server
    plugs:
      - network-bind
      - home
  change-passwords:
    command: bin/change-passwords

parts:
  crystal-gchat-server:
    source: ./
    plugin: crystal
    build-packages:
      - git
      - libssl-dev
